### ISSUE TITLE
Add posting results to X

### ISSUE THREAD

**Issue by LukesterWad** [MaxHearnden/compsoc-calculator#10]
It would be a real value add to allow posting results of calculation to X - the everything app.

A good way to do this would be IoT integration. Maybe you could even use generative AI to generate a description of the calculation.

**Comment by MaxHearnden** [comment]
We'll circle back on that.

**Comment by LukesterWad** [comment]
It's been 1 minute since this feature request was made. Is there any progress to report?

**Comment by LukesterWad** [comment]
I'll assume this is a blocker.

**Comment by MaxHearnden** [comment]
no
