### ISSUE TITLE
Fix equals and modulus Buttons

### ISSUE THREAD

**Issue by orkfpot** [MaxHearnden/compsoc-calculator#11]
Add a button that allows the user to view the results of all the mathematical operations until now

**Comment by orkfpot** [comment]
![Screenshot_20241105_183028](https://github.com/user-attachments/assets/f96d8597-6bcb-4cee-9f13-47225e0399df)

**Comment by orkfpot** [comment]
the equals and modulus buttons don't appeoar

**Comment by MaxHearnden** [comment]
Fixed

**Comment by orkfpot** [comment]
yay!
